---
- name: Conectar a AKS y desplegar MySQL (Pruebas)
  hosts: localhost
  tasks:
    - name: Obtener credenciales de AKS (kubectl)
      command: az aks get-credentials --resource-group DVR --name dvrAksCluster --overwrite-existing

    - name: Aplicar el manifiesto MySQL en el cluster
      k8s:
        kubeconfig: "{{ ansible_env.HOME }}/.kube/config"
        state: present
        src: mysql-deploy.yaml
