# crear-nginx.yml
- name: Construir la imagen de Nginx en localhost
  hosts: localhost
  tasks:
    - name: Crear directorio para el Dockerfile y el index.html
      file:
        path: "{{ ansible_env.HOME }}/nginx-podman"
        state: directory

    - name: Copiar el Dockerfile a localhost
      copy:
        content: |
          # Dockerfile
          FROM docker.io/library/nginx:latest
          COPY index.html /usr/share/nginx/html/index.html
        dest: "{{ ansible_env.HOME }}/nginx-podman/Dockerfile"

    - name: Copiar el archivo index.html a localhost
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>CURSO DEVOPS & CLOUD. UNIR</title>
          </head>
          <body>
              <h1>Práctica CP2</h1>
              <p>Este es un servidor Nginx en un contenedor.</p>
          </body>
          </html>
        dest: "{{ ansible_env.HOME }}/nginx-podman/index.html"

    - name: Construir la imagen de Nginx con Podman
      shell: |
        podman build -t nginx-dvr {{ ansible_env.HOME }}/nginx-podman

