# nginx.yml
- name: Instalar y configurar Nginx
  hosts: webserver  # Grupo de servidores definido en el inventario
  become: yes  # Ejecutar tareas con privilegios de superusuario
  tasks:
    - name: Actualizar el sistema
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar Nginx
      apt:
        name: nginx
        state: present

    - name: Habilitar e iniciar Nginx
      service:
        name: nginx
        enabled: yes
        state: started

    - name: Crear una página de inicio básica
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Bienvenido</title>
          </head>
          <body>
              <h1>¡Hola, mundo!</h1>
              <p>Este es un servidor Nginx configurado con Ansible.</p>
          </body>
          </html>
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Configurar Nginx para servir la página de inicio
      copy:
        content: |
          server {
              listen 80;
              server_name _;
              root /var/www/html;
              index index.html;
              location / {
                  try_files $uri $uri/ =404;
              }
          }
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'
      notify: Reiniciar Nginx

  handlers:
    - name: Reiniciar Nginx
      service:
        name: nginx
        state: restarted
