- name: Construir la imagen de Nginx mejorada
  hosts: localhost
  vars_files:
    - /home/beetlebum/cp2/ansible/secrets.yml  # Carga las variables sensibles

  tasks:
    - name: Crear directorios para la configuración de Nginx
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - ./nginx-config
        - ./nginx-config/html
        - ./nginx-config/certs
        - ./nginx-config/auth
        - ./nginx-config/conf.d

    - name: Copiar el Dockerfile
      ansible.builtin.copy:
        content: |
          # Dockerfile
          FROM docker.io/library/nginx:latest
          COPY ./nginx-config/conf.d /etc/nginx/conf.d/
          COPY ./nginx-config/html /usr/share/nginx/html/
          COPY ./nginx-config/auth /etc/nginx/auth/
          COPY ./nginx-config/certs /etc/nginx/certs/
        dest: ./Dockerfile.nginx

    - name: Crear archivo index.html con UTF-8
      ansible.builtin.copy:
        content: |
          <!DOCTYPE html>
          <html lang="es">
          <head>
              <meta charset="UTF-8">
              <title>UNIR</title>
          </head>
          <body>
              <h1>DEVOPS & CLOUD | CP2 AZURE - David Vázquez</h1>
              <p>Este es un servidor Nginx seguro con autenticación básica.</p>
          </body>
          </html>
        dest: ./nginx-config/html/index.html

    - name: Generar clave privada para el certificado
      community.crypto.openssl_privatekey:
        path: ./nginx-config/certs/nginx-selfsigned.key
        size: 2048

    - name: Generar certificado autofirmado
      community.crypto.x509_certificate:
        path: ./nginx-config/certs/nginx-selfsigned.crt
        privatekey_path: ./nginx-config/certs/nginx-selfsigned.key
        provider: selfsigned

    - name: Crear archivo de contraseñas para autenticación básica
      community.general.htpasswd:
        path: ./nginx-config/auth/.htpasswd
        name: "{{ usuario_nginx }}"
        password: "{{ pass_nginx }}"
        crypt_scheme: bcrypt

    - name: Copiar configuración de Nginx
      ansible.builtin.copy:
        content: |
          server {
              listen 443 ssl;
              server_name localhost;

              ssl_certificate /etc/nginx/certs/nginx-selfsigned.crt;
              ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;

              location / {
                  auth_basic "Acceso restringido";
                  auth_basic_user_file /etc/nginx/auth/.htpasswd;
                  root /usr/share/nginx/html;
                  index index.html;
              }
          }
        dest: ./nginx-config/conf.d/default.conf

    - name: Construir la imagen de Nginx con Podman
      containers.podman.podman_image:
        path: .
        name: nginx-dvr:casopractico2
        build:
          file: Dockerfile.nginx
