# desplegar-nginx-vm.yml
- name: Configurar la VM Linux para ejecutar Nginx desde el ACR
  hosts: vm_azure
  become: yes
  vars_files:
    - /home/beetlebum/cp2/ansible/secrets.yml  # Carga las variables sensibles desde un archivo encriptado con Ansible Vault
  vars:
    acr_username: "dvrAcrRegistry"
    acr_registry: "dvrAcrRegistry.azurecr.io"
    image_name: "nginx-dvr"
    image_tag: "casopractico2"
  tasks:
    - name: Instalar Podman
      apt:
        name: podman
        state: present
        update_cache: yes

    - name: Autenticarse en el ACR con podman
      shell: |
        podman login {{ acr_registry }} --username {{ acr_username }} --password {{ acr_password }}
      no_log: true  # Evitar mostrar la contraseña en los logs

    - name: Descargar la imagen de Nginx desde el ACR
      shell: |
        podman pull {{ acr_registry }}/nginx/{{ image_name }}:{{ image_tag }}

    - name: Ejecutar el contenedor de Nginx
      shell: |
        podman run -d --name nginx -p 80:80 -p 443:443 {{ acr_registry }}/nginx/{{ image_name }}:{{ image_tag }}
