---
- name: Desplegar imagen MySQL en ACR
  hosts: localhost
  #become: yes
  tasks:
    - name: Autenticarse en el ACR
      command: >
        podman login dvrAcrRegistry.azurecr.io
        --username dvrAcrRegistry
        --password ******
      args:
        creates: /root/.docker/config.json  # Evita repetir el login si ya está autenticado

    - name: Crear Dockerfile
      copy:
        content: |
          # Dockerfile.mysql
          FROM docker.io/library/mysql:8.0

          # Variables de entorno para MySQL
          ENV MYSQL_ROOT_PASSWORD=******
          ENV MYSQL_DATABASE=******
          ENV MYSQL_USER=******
          ENV MYSQL_PASSWORD=******

          # Puerto expuesto
          EXPOSE 3306
        dest: ./Dockerfile.mysql

    - name: Construir la imagen de MySQL
      command: >
        podman build -t mysql:casopractico2 -f Dockerfile.mysql .

    - name: Etiquetar la imagen
      command: >
        podman tag mysql:casopractico2
        dvrAcrRegistry.azurecr.io/mysql/casopractico2:casopractico2

    - name: Subir la imagen al ACR
      command: >
        podman push dvrAcrRegistry.azurecr.io/mysql/casopractico2:casopractico2
