# Dockerfile.mysql
FROM docker.io/library/mysql:8.0

# Variables de entorno para MySQL
ENV MYSQL_ROOT_PASSWORD=******
ENV MYSQL_DATABASE=******
ENV MYSQL_USER=******
ENV MYSQL_PASSWORD=******

# Puerto expuesto
EXPOSE 3306
